spring.application.name=backend

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/recruithub
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080

# Zoho CRM
zoho.crm.client-id=${ZOHO_CLIENT_ID}
zoho.crm.client-secret=${ZOHO_CLIENT_SECRET}
zoho.crm.refresh-token=${ZOHO_REFRESH_TOKEN}
zoho.crm.api-domain=https://www.zohoapis.com